SET IDENTITY_INSERT [dbo].[Reviews] ON
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1, 1, 3, N'Good product', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (2, 1, 4, N'The product is excellent!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1002, 1, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1003, 1, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1004, 1, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1005, 1, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1006, 1, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1007, 2, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1008, 2, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1009, 2, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1010, 2, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1011, 2, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1012, 3, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1013, 3, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1014, 3, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1015, 3, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1016, 3, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1017, 4, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1018, 4, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1019, 4, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1020, 4, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1021, 4, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1022, 5, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1023, 5, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1024, 5, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1025, 5, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1026, 5, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1027, 6, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1028, 6, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1029, 6, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1030, 6, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1031, 6, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1032, 7, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1033, 7, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1034, 7, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1035, 7, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1036, 7, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1037, 8, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1038, 8, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1039, 8, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1040, 8, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1041, 8, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1042, 9, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1043, 9, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1044, 9, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1045, 9, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1046, 9, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1047, 10, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1048, 10, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1049, 10, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1050, 10, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1051, 10, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1052, 11, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1053, 11, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1054, 11, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1055, 11, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1056, 11, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1057, 12, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1058, 12, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1059, 12, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1060, 12, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1061, 12, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1062, 13, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1063, 13, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1064, 13, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1065, 13, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1066, 13, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1067, 14, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1068, 14, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1069, 14, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1070, 14, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1071, 14, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1072, 15, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1073, 15, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1074, 15, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1075, 15, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1076, 15, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1077, 16, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1078, 16, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1079, 16, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1080, 16, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1081, 16, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1082, 17, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1083, 17, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1084, 17, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1085, 17, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1086, 17, 7, N'did not like it a lot', N'Poor')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1087, 18, 3, N'great product, loved the material.', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1088, 18, 4, N'loved the fit!', N'Good')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1089, 18, 5, N'good product, liked it.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1090, 18, 6, N'good but can do better.', N'Average')
INSERT INTO [dbo].[Reviews] ([Review_ID], [Product_ID], [Customer_ID], [Description], [Liking]) VALUES (1091, 18, 7, N'did not like it a lot', N'Poor')
SET IDENTITY_INSERT [dbo].[Reviews] OFF
