//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_ID { get; set; }
        public int Order_NO { get; set; }
        public int Customer_ID { get; set; }
        public int Cart_ID { get; set; }
        public System.DateTime Order_Date { get; set; }
        public int Base_Price { get; set; }
        public int Shipping_price { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
